package com.person124.sm.common;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.Potion;
import net.minecraftforge.common.EnumHelper;
import net.minecraftforge.common.MinecraftForge;

import com.person124.sm.block.BlockBasic;
import com.person124.sm.block.BlockSummonCircle;
import com.person124.sm.element.Darkness;
import com.person124.sm.element.Earth;
import com.person124.sm.element.Fragor;
import com.person124.sm.element.Limbo;
import com.person124.sm.element.Water;
import com.person124.sm.event.EventEntityDamage;
import com.person124.sm.event.EventFreezePotion;
import com.person124.sm.item.ItemBasic;
import com.person124.sm.potion.PotionFreeze;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "simplemagic", name = "Simple Magic", version = "0.1.0")
@NetworkMod(clientSideRequired = true)
public class mod_SimpleMagic {

	@Instance(value = "simplemagic")
	public static mod_SimpleMagic instance;

	@SidedProxy(clientSide = "com.person124.sm.client.ClientProxy", serverSide = "com.person124.sm.common.CommonProxy")
	public static CommonProxy proxy;

	private static final int id = 600;
	public static final int earthID = id + 20;
	public static final int limboID = earthID + 20;
	public static final int fragorID = limboID + 20;
	public static final int waterID = fragorID + 20;
	public static final int darkID = waterID + 20;
	public static EnumArmorMaterial ELEMENTMAIN = EnumHelper.addArmorMaterial("ELEMENTMAIN", 15, new int[] { 2, 5, 4, 1 }, 0);
	public static EnumArmorMaterial ELEMENTALMIGHTY = EnumHelper.addArmorMaterial("ELEMENTALMIGHTY", 25, new int[] { 2, 5, 4, 1 }, 0);
	public static EnumArmorMaterial ELEMENTMINOR = EnumHelper.addArmorMaterial("ELEMENTMINOR", 10, new int[] { 2, 5, 4, 1 }, 0);
	public static EnumArmorMaterial ELEMENTSUB = EnumHelper.addArmorMaterial("ELEMENTSUB", 20, new int[] { 2, 5, 4, 1 }, 0);
	public static CreativeTabs smTab = new SMTab(CreativeTabs.getNextID(), "SMTab");

	public static final Item magicDust = new ItemBasic(id, "sm-magicdust", 64, smTab);
	public static final Block magicDustBlock = new BlockBasic(id + 1, Material.clay, "sm-magicblock", smTab, 2.0F, Block.soundClothFootstep, 2.0F, false);
	public static final Item magicOrb = new ItemBasic(id + 2, "sm-magicorb", 64, smTab);
	public static final Block summonCircle = new BlockSummonCircle(id + 3, Material.cloth, "sm-summoncircleblock", smTab, 0.8F, Block.soundClothFootstep, 0.0F, false, 0);
	public static final Block summonCircleMid = new BlockSummonCircle(id + 4, Material.cloth, "sm-summoncircleblockmid", mod_SimpleMagic.smTab, 0.8F, Block.soundClothFootstep, 0.0F, false, 1);
	public static final Block summonCircleEdge = new BlockSummonCircle(id + 5, Material.cloth, "sm-summoncircleedge", null, 1.0F, Block.soundClothFootstep, 1.5F, false, 2);
	public static final Block summonCircleEdgeMid = new BlockSummonCircle(id + 6, Material.cloth, "sm-summoncircleedgemid", null, 1.0F, Block.soundClothFootstep, 1.5F, false, 3);
	public static final Item magicIngot = new ItemBasic(id + 7, "sm-magicingot", 64, smTab);

	public static Potion freezePotion;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {

		event.getModMetadata().autogenerated = false;
		event.getModMetadata().url = "http://www.planetminecraft.com/mod/simple-magic-v1/";
		event.getModMetadata().credits = "Thank you ThirstBuster on PMC for some of the textures.";
		event.getModMetadata().authorList.add("person124");
		event.getModMetadata().description = "Magic is Simple, is it not?";
		event.getModMetadata().logoFile = "/assets/simplemagic/textures/logo.png";

		Potion[] potionTypes = null;

		for (Field f : Potion.class.getDeclaredFields()) {
			f.setAccessible(true);
			try {
				if (f.getName().equals("potionTypes")) {
					Field modfield = Field.class.getDeclaredField("modifiers");
					modfield.setAccessible(true);
					modfield.setInt(f, f.getModifiers() & ~Modifier.FINAL);

					potionTypes = (Potion[]) f.get(null);
					final Potion[] newPotionTypes = new Potion[256];
					System.arraycopy(potionTypes, 0, newPotionTypes, 0, potionTypes.length);
					f.set(null, newPotionTypes);
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
		}

	}

	@EventHandler
	public void load(FMLInitializationEvent event) {
		proxy.load();
		load();
		Earth.load();
		Limbo.load();
		Fragor.load();
		Water.load();
		Darkness.load();

		MinecraftForge.EVENT_BUS.register(new EventEntityDamage());
		MinecraftForge.EVENT_BUS.register(new EventFreezePotion());

		// TickRegistry.registerTickHandler(new RenderPotionFreeze(),
		// Side.CLIENT);

		freezePotion = new PotionFreeze(32, false, 0, 0, 1, "potion.freezepotion");
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {

	}

	public void load() {
		LanguageRegistry.addName(magicDust, "Magic Dust");
		GameRegistry.addSmelting(Item.redstone.itemID, new ItemStack(magicDust, 5), 0.8F);

		LanguageRegistry.addName(magicDustBlock, "Magic Dust Block");
		GameRegistry.addRecipe(new ItemStack(magicDustBlock, 1), new Object[] { "***", "***", "***", '*', new ItemStack(magicDust) });
		GameRegistry.addShapelessRecipe(new ItemStack(magicDust, 9), new ItemStack(magicDustBlock));
		MinecraftForge.setBlockHarvestLevel(magicDustBlock, "pickaxe", 1);
		GameRegistry.registerBlock(magicDustBlock);

		LanguageRegistry.addName(magicOrb, "Magic Orb");
		GameRegistry.addRecipe(new ItemStack(magicOrb), new Object[] { "*&*", "&^&", "*&*", '*', new ItemStack(Block.glass), '&', new ItemStack(magicDust), '^', new ItemStack(magicDustBlock) });

		LanguageRegistry.addName(summonCircle, "Summoning Square Piece - Side");
		GameRegistry.registerBlock(summonCircle);
		GameRegistry.addRecipe(new ItemStack(mod_SimpleMagic.summonCircle, 1), new Object[] { "***", "*%*", "***", '*', new ItemStack(Block.cloth, 1, 15), '%', new ItemStack(Item.redstone, 1) });

		LanguageRegistry.addName(summonCircleMid, "Summoning Square Piece - Middle");
		GameRegistry.registerBlock(summonCircleMid);
		GameRegistry.addRecipe(new ItemStack(mod_SimpleMagic.summonCircleMid, 1), new Object[] { "*&*", "*%*", "***", '*', new ItemStack(Block.cloth, 1, 15), '&', new ItemStack(mod_SimpleMagic.magicOrb, 1), '%', new ItemStack(Item.redstone, 1) });

		LanguageRegistry.addName(summonCircleEdge, "You shouldn't have this!");
		GameRegistry.registerBlock(summonCircleEdge);

		LanguageRegistry.addName(summonCircleEdgeMid, "You shouldn't have this!");
		GameRegistry.registerBlock(summonCircleEdgeMid);

		LanguageRegistry.addName(magicIngot, "Magic Ingot");
		GameRegistry.addSmelting(mod_SimpleMagic.magicDustBlock.blockID, new ItemStack(mod_SimpleMagic.magicIngot, 1), 0.0F);

		LanguageRegistry.instance().addStringLocalization("potion.freezepotion", "Freeze");
	}

	// *Earth and *Limbo
	// *Fire and *Fragor(Explosive/Creeper)
	// *Water and Darkness
	// Time and Air
	// Life and Porcus(Pig)
	// Space and Vacca(I think cow?)
	// Light and Aranea(spider)
	// Death

}
